# slug, name, pattern, muscles(primary first), equipment, tier, area, barbell, cue
LIB = [
 # ---- squat pattern ----
 ("back-squat","Back Squat","squat",["quads","glutes","core"],"barbell","core","lower",1,
  "Bar on your upper back, feet shoulder-width. Sit down between your hips, knees tracking over your toes. Go as deep as you can keep a flat back."),
 ("goblet-squat","Goblet Squat","squat",["quads","glutes","core"],"dumbbell","core","lower",0,
  "Hold one dumbbell at your chest. Sit down between your hips, elbows inside your knees, chest tall."),
 ("leg-press","Leg Press","squat",["quads","glutes"],"machine","core","lower",0,
  "Feet shoulder-width on the platform. Lower until your knees are near 90 degrees. Never slam your knees straight at the top."),
 ("hack-squat","Hack Squat Machine","squat",["quads","glutes"],"machine","core","lower",0,
  "Shoulders under the pads, feet mid-platform. Lower slowly, push through the whole foot."),
 ("split-squat","Bulgarian Split Squat","squat",["quads","glutes"],"dumbbell","accessory","lower",0,
  "Back foot on a bench, drop straight down, front knee tracking over the foot. Hold the rail if you wobble."),
 ("walking-lunge","Walking Lunge","squat",["quads","glutes"],"dumbbell","accessory","lower",0,
  "Long step forward, back knee towards the floor, stand up through the front heel."),

 # ---- hinge pattern ----
 ("deadlift","Deadlift","hinge",["hamstrings","glutes","back"],"barbell","core","lower",1,
  "Bar over mid-foot, shins close, flat back, chest up. Push the floor away instead of yanking. Stop the set the moment your back rounds."),
 ("romanian-deadlift","Romanian Deadlift","hinge",["hamstrings","glutes"],"barbell","core","lower",1,
  "Soft knees, push your hips back and slide the bar down your thighs. Stop when you feel the stretch behind your knees."),
 ("db-rdl","Dumbbell Romanian Deadlift","hinge",["hamstrings","glutes"],"dumbbell","core","lower",0,
  "Soft knees, hinge at the hips, dumbbells sliding down your thighs, back flat throughout."),
 ("hip-thrust","Hip Thrust","hinge",["glutes","hamstrings"],"barbell","core","lower",1,
  "Shoulders on a bench, bar padded across the hips. Drive through your heels, squeeze at the top, keep your ribs down."),
 ("hip-thrust-m","Hip Thrust Machine","hinge",["glutes","hamstrings"],"machine","core","lower",0,
  "Back against the pad, belt or bar across your hips. Drive through your heels, squeeze at the top, ribs down."),
 ("single-leg-rdl","Single-leg Romanian Deadlift","hinge",["hamstrings","glutes"],"dumbbell","accessory","lower",0,
  "Stand on one leg, hinge forward reaching the dumbbell towards the floor, back flat. Hold something for balance."),
 ("glute-bridge","Glute Bridge","hinge",["glutes","hamstrings"],"bodyweight","accessory","lower",0,
  "On your back, feet flat and close to your backside. Drive the hips up, squeeze, lower slowly."),
 ("back-extension","Back Extension","hinge",["hamstrings","glutes","back"],"machine","accessory","lower",0,
  "Pads at your hips, fold forward with a flat back, squeeze your glutes to come up. No swinging."),
 ("leg-curl","Leg Curl","hinge",["hamstrings"],"machine","accessory","lower",0,
  "Pad just above your heels. Curl towards your backside, lower slowly."),
 ("glute-bridge-m","Glute Machine","hinge",["glutes"],"machine","accessory","lower",0,
  "Feet flat, drive the hips up, pause at the top, lower under control."),

 # ---- horizontal push ----
 ("bench-press","Bench Press","hpush",["chest","triceps","shoulders"],"barbell","core","upper",1,
  "Shoulder blades pinched back, feet flat. Bar to mid-chest, elbows about 45 degrees from your body. Use the rack safeties or ask for a spot."),
 ("db-bench","Dumbbell Bench Press","hpush",["chest","triceps","shoulders"],"dumbbell","core","upper",0,
  "Dumbbells at chest height, press up until they nearly touch. Keep your wrists straight over your elbows."),
 ("chest-press-m","Chest Press Machine","hpush",["chest","triceps"],"machine","core","upper",0,
  "Set the seat so the handles sit at chest height. Press out smoothly, don't snap your elbows straight."),
 ("incline-db","Incline Dumbbell Press","hpush",["chest","shoulders"],"dumbbell","accessory","upper",0,
  "Bench at about 30 degrees. Press up and slightly together, control the way down."),
 ("db-fly","Dumbbell Fly","hpush",["chest"],"dumbbell","accessory","upper",0,
  "Lie back, soft elbows, open your arms wide then bring them together above your chest."),
 ("push-up","Push-ups","hpush",["chest","triceps","core"],"bodyweight","accessory","upper",0,
  "Hands under your shoulders, body in a straight line. Hands on a bench makes it easier."),
 ("cable-fly","Cable Fly","hpush",["chest"],"cable","accessory","upper",0,
  "Soft elbows, bring the handles together in front of your chest like you're hugging someone."),

 # ---- vertical push ----
 ("ohp","Overhead Press","vpush",["shoulders","triceps"],"barbell","core","upper",1,
  "Bar at collarbone height, stomach tight. Press up and slightly back so it finishes over your ears."),
 ("db-shoulder-press","Dumbbell Shoulder Press","vpush",["shoulders","triceps"],"dumbbell","core","upper",0,
  "Dumbbells at shoulder height, press overhead without arching your lower back."),
 ("shoulder-press-m","Shoulder Press Machine","vpush",["shoulders","triceps"],"machine","core","upper",0,
  "Seat height so the handles start at shoulder level. Press up without shrugging."),
 ("lateral-raise","Lateral Raise","vpush",["shoulders"],"dumbbell","accessory","upper",0,
  "Light dumbbells, lift out to the sides to shoulder height with a slight bend in the elbows."),

 # ---- horizontal pull ----
 ("barbell-row","Barbell Row","hpull",["back","biceps"],"barbell","core","upper",1,
  "Hinge forward with a flat back, pull the bar to your lower ribs, elbows close to your body."),
 ("db-row","One-arm Dumbbell Row","hpull",["back","biceps"],"dumbbell","core","upper",0,
  "One knee and hand on a bench, flat back, pull the dumbbell to your hip."),
 ("seated-row-m","Seated Row Machine","hpull",["back","biceps"],"machine","core","upper",0,
  "Chest against the pad, pull the handles to your ribs, squeeze your shoulder blades together."),
 ("cable-row","Cable Row","hpull",["back","biceps"],"cable","core","upper",0,
  "Sit tall, pull to your belly button, shoulders back, control the return."),
 ("face-pull","Face Pull","hpull",["shoulders","back"],"cable","accessory","upper",0,
  "Rope at eye height. Pull towards your forehead with elbows high and wide. Light weight, slow."),
 ("rear-delt-fly","Rear Delt Fly","hpull",["shoulders","back"],"dumbbell","accessory","upper",0,
  "Hinge forward, light dumbbells, open your arms out to the sides like wings."),
 ("shrug","Shrug","hpull",["back"],"dumbbell","accessory","upper",0,
  "Lift your shoulders straight up towards your ears, pause, lower slowly. No rolling."),

 # ---- vertical pull ----
 ("lat-pulldown","Lat Pulldown","vpull",["back","biceps"],"machine","core","upper",0,
  "Thighs under the pad. Pull the bar to your collarbone leading with the elbows. No swinging."),
 ("chin-up","Chin-ups","vpull",["back","biceps"],"bodyweight","core","upper",0,
  "Palms facing you, hang with straight arms, pull until your chin clears the bar. The assisted machine or a band is fine."),
 ("straight-arm-pd","Straight-arm Pulldown","vpull",["back"],"cable","accessory","upper",0,
  "Arms nearly straight, sweep the bar down to your thighs using your back, not your arms."),

 # ---- arms ----
 ("curl","Dumbbell Curl","arms",["biceps"],"dumbbell","accessory","upper",0,
  "Elbows still at your sides, no swinging. Lower slower than you lift."),
 ("hammer-curl","Hammer Curl","arms",["biceps"],"dumbbell","accessory","upper",0,
  "Palms facing each other the whole way. Elbows pinned to your sides."),
 ("tricep-pushdown","Tricep Pushdown","arms",["triceps"],"cable","accessory","upper",0,
  "Elbows pinned to your sides. Straighten the arms fully, control the way back."),
 ("overhead-tricep","Overhead Tricep Extension","arms",["triceps"],"dumbbell","accessory","upper",0,
  "One dumbbell behind your head, elbows pointing up, straighten the arms."),

 # ---- calves ----
 ("calf-raise","Calf Raise","calves",["calves"],"machine","accessory","lower",0,
  "Full stretch at the bottom, pause for a second at the top of every rep."),
 ("standing-calf","Standing Calf Raise","calves",["calves"],"dumbbell","accessory","lower",0,
  "Balls of your feet on a step, heels down for a stretch, up onto your toes and hold."),
 ("leg-extension","Leg Extension","squat",["quads"],"machine","accessory","lower",0,
  "Pad above your ankles. Straighten the legs, pause a beat, lower under control."),

 # ---- core ----
 ("plank","Plank","core",["core"],"bodyweight","accessory","core",0,
  "Straight line from head to heels. Squeeze your glutes so your hips don't sag."),
 ("hanging-leg-raise","Hanging Leg Raise","core",["core"],"bodyweight","accessory","core",0,
  "Hang still, then lift your legs without swinging. Bend the knees if straight legs are too hard."),
 ("cable-crunch","Cable Crunch","core",["core"],"cable","accessory","core",0,
  "Kneel facing the machine, rope by your head, curl your ribs down towards your hips."),
 ("dead-bug","Dead Bug","core",["core"],"bodyweight","accessory","core",0,
  "On your back, lower opposite arm and leg slowly while keeping your lower back flat on the floor."),
 ("pallof-press","Pallof Press","core",["core"],"cable","accessory","core",0,
  "Stand side-on to the cable, press the handle straight out and resist the twist."),
 ("ab-machine","Ab Machine","core",["core"],"machine","accessory","core",0,
  "Set the seat, curl your ribs down towards your hips, control the return."),
 ("farmer-carry","Farmer's Carry","core",["core","back"],"dumbbell","accessory","core",0,
  "A heavy dumbbell in each hand. Stand tall, shoulders down, walk steady without leaning."),
# ---- added to widen the library ----
 ("front-squat","Front Squat","squat",["quads","core"],"barbell","core","lower",1,
  "Bar across the front of your shoulders, elbows high. Sit straight down, chest up."),
 ("box-squat","Box Squat","squat",["quads","glutes"],"barbell","core","lower",1,
  "Sit back onto a box at about parallel, pause, then drive up. Good for learning depth."),
 ("step-up","Step-up","squat",["quads","glutes"],"dumbbell","accessory","lower",0,
  "Whole foot on the bench, drive through that heel, control the way down."),
 ("sissy-squat","Sissy Squat","squat",["quads"],"bodyweight","accessory","lower",0,
  "Hold a rail, lean back and bend the knees forward. Slow, small range at first."),
 ("trap-bar-deadlift","Trap Bar Deadlift","hinge",["hamstrings","glutes","quads"],"barbell","core","lower",1,
  "Stand inside the frame, handles at your sides. Easier on the lower back than a straight bar."),
 ("sumo-deadlift","Sumo Deadlift","hinge",["glutes","hamstrings"],"barbell","core","lower",1,
  "Wide stance, hands inside your knees. Push the floor apart as you stand."),
 ("good-morning","Good Morning","hinge",["hamstrings","glutes"],"barbell","accessory","lower",1,
  "Light bar on your back, hinge forward with soft knees and a flat back. Start very light."),
 ("kettlebell-swing","Kettlebell Swing","hinge",["glutes","hamstrings"],"dumbbell","accessory","lower",0,
  "Hinge, not squat. Snap the hips through and let the bell float — arms stay relaxed."),
 ("incline-bench","Incline Bench Press","hpush",["chest","shoulders"],"barbell","core","upper",1,
  "Bench at about 30 degrees. Bar to the top of your chest, elbows tucked slightly."),
 ("close-grip-bench","Close-grip Bench Press","hpush",["triceps","chest"],"barbell","core","upper",1,
  "Hands about shoulder width. Elbows close to your sides the whole way."),
 ("dip","Dips","hpush",["chest","triceps"],"bodyweight","accessory","upper",0,
  "Lean forward slightly for chest, upright for triceps. Use the assisted machine if you need to."),
 ("machine-fly","Pec Deck","hpush",["chest"],"machine","accessory","upper",0,
  "Elbows at chest height on the pads. Squeeze the handles together, control the way back."),
 ("arnold-press","Arnold Press","vpush",["shoulders"],"dumbbell","accessory","upper",0,
  "Start with palms facing you, rotate outwards as you press overhead."),
 ("push-press","Push Press","vpush",["shoulders","triceps"],"barbell","core","upper",1,
  "A small dip of the knees, then drive the bar overhead. Lets you handle more than a strict press."),
 ("cable-lateral","Cable Lateral Raise","vpush",["shoulders"],"cable","accessory","upper",0,
  "Cable at the bottom, lift out to the side to shoulder height, slow on the way down."),
 ("chest-supported-row","Chest-supported Row","hpull",["back","biceps"],"machine","core","upper",0,
  "Chest on the pad so you cannot cheat with your lower back. Pull to your ribs."),
 ("t-bar-row","T-bar Row","hpull",["back","biceps"],"barbell","core","upper",1,
  "Hinge over the bar, flat back, pull the handles to your stomach."),
 ("inverted-row","Inverted Row","hpull",["back","biceps"],"bodyweight","accessory","upper",0,
  "Bar at hip height, body straight, pull your chest to the bar. Bend your knees to make it easier."),
 ("neutral-pulldown","Neutral-grip Pulldown","vpull",["back","biceps"],"machine","core","upper",0,
  "Palms facing each other. Easier on the shoulders than a wide grip."),
 ("pull-up","Pull-ups","vpull",["back"],"bodyweight","core","upper",0,
  "Palms facing away, hang with straight arms, pull until your chin clears the bar."),
 ("preacher-curl","Preacher Curl","arms",["biceps"],"dumbbell","accessory","upper",0,
  "Arms flat on the pad. No swinging is even possible, which is the point."),
 ("cable-curl","Cable Curl","arms",["biceps"],"cable","accessory","upper",0,
  "Constant tension the whole way. Elbows stay at your sides."),
 ("skullcrusher","Skullcrusher","arms",["triceps"],"barbell","accessory","upper",0,
  "Lying down, lower the bar to your forehead by bending only at the elbow."),
 ("dip-machine","Tricep Dip Machine","arms",["triceps"],"machine","accessory","upper",0,
  "Seat set so the handles are at chest height. Press down, elbows close."),
 ("seated-calf","Seated Calf Raise","calves",["calves"],"machine","accessory","lower",0,
  "Knees bent under the pad. Full stretch down, pause at the top."),
 ("ab-wheel","Ab Wheel","core",["core"],"bodyweight","accessory","core",0,
  "From your knees, roll out only as far as you can keep your back flat. Very short range at first."),
 ("side-plank","Side Plank","core",["core"],"bodyweight","accessory","core",0,
  "On one forearm, hips stacked and lifted. Hold, then swap sides."),
 ("russian-twist","Russian Twist","core",["core"],"dumbbell","accessory","core",0,
  "Sit leaning back, feet up if you can, rotate the weight side to side under control."),
 # ---- added after the UX audit: the library was the thinnest part of the app ----
   ("hip-abduction","Hip Abduction Machine","hinge",["glutes"],"machine","accessory","lower",0,
  "Sit tall, push your knees apart against the pads, pause, return slowly."),
 ("glute-kickback","Glute Kickback","hinge",["glutes"],"machine","accessory","lower",0,
  "Hips square, drive one leg back and up, squeeze at the top. No arching your lower back."),
 ("kb-swing","Kettlebell Swing","hinge",["glutes","hamstrings"],"dumbbell","accessory","lower",0,
  "Hinge at the hips, snap them forward. The arms just hold on — it is not a lift with the shoulders."),
       ("machine-lateral","Lateral Raise Machine","vpush",["shoulders"],"machine","accessory","upper",0,
  "Pads on the outside of your arms, lift out to shoulder height, lower slowly."),
    ("assisted-pullup","Assisted Pull-up Machine","vpull",["back","biceps"],"machine","core","upper",0,
  "Kneel on the pad, hang with straight arms, pull until your chin clears the bar. More assistance is a lighter pull."),
        ("reverse-crunch","Reverse Crunch","core",["core"],"bodyweight","accessory","core",0,
  "On your back, knees bent, curl your hips off the floor towards your chest. Slow, not swung."),
 ("suitcase-carry","Suitcase Carry","core",["core"],"dumbbell","accessory","core",0,
  "One heavy dumbbell in one hand. Walk tall without leaning away from it."),
 ]